version: '2'
services:
  staywoke_api:
    build:
      context: .
    links:
      - database
      - elasticsearch
      - redis
    volumes:
      - .:/home/staywoke/api/
      - /home/staywoke/api/node_modules
    environment:
      API_NODE_ENV: docker
    ports:
      - 5000:5000
    command: ["./scripts/docker-compose/wait-for-it.sh", "elasticsearch:9200", "--timeout=30", "--", "./scripts/docker-compose/start.sh"]
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: c1v1Ls3rv1c3s
      MYSQL_DATABASE: staywoke_api
  elasticsearch:
    image: elasticsearch:1.7.5
  redis:
    image: redis:3.2.4