services:
  docker_api:
    platform: linux/x86_64
    tty: true
    build:
      context: .
    links:
      - database
      - elasticsearch
    volumes:
      - .:/home/developer/api/
      - /home/developer/api/node_modules
    environment:
      API_NODE_ENV: docker
      NPM_CONFIG_LOGLEVEL: silent
    ports:
      - "5001:5001"
    command: ["./scripts/docker-compose/wait-for-it.sh", "elasticsearch:9200", "--timeout=30", "--", "./scripts/docker-compose/start.sh"]
    networks:
      - api-network
  database:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "8083:3306"
    environment:
      MYSQL_DATABASE: docker_api
      MYSQL_PASSWORD: d0cK3r^4p1
      MYSQL_ROOT_PASSWORD: d0cK3r^4p1
      MYSQL_USER: docker_api
    networks:
      - api-network
  elasticsearch:
    platform: linux/x86_64
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - api-network
networks:
  api-network:
    driver: bridge
